server:
  # 服务端口
  port: 8090
  servlet:
    context-path: /
spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "root"
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.214.19:3306/fast13?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
# 配置 MyBatis
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.example.d2.entity
  configuration:
    map-underscore-to-camel-case: true